### ISSUE TITLE
Mod added skills break the editor - v0.8beta

### ISSUE THREAD

**Issue by JordanR-Surge** [Wufflez/Loki#10]
"Error loading from character file: Unrecognised skill type (Paarameter 'type')
Actual value was 242"

Custom skills added by [Skill Injector](https://www.nexusmods.com/valheim/mods/341) break the editor when attempting to load the save. The only skill I'm currently running is the [gathering skill](https://www.nexusmods.com/valheim/mods/342) so that should give you a place to test from.

**Comment by Kiaos** [comment]
Can confirm a diving mod broke this editor by making a new skill called diving

**Comment by BrandonT80** [comment]
Can confirm anything adding skills breaks this completely.

**Comment by BrandonT80** [comment]
I created a pull request that fixes this issue at least temporarily. While it does not directly make it compatible it at least allows use of the program without having the plugin break it.

**Comment by Wufflez** [comment]
Closing this Issue because it should be OK now in recent versions with the changes made by @BrandonT80
