### ISSUE TITLE
No executable 

### ISSUE THREAD

**Issue by TheKoTech** [Wufflez/Loki#12]
Where's the Loki.exe file?
![image](https://user-images.githubusercontent.com/92980051/143010896-afb94b25-d13c-4ddf-8512-f3d67783181c.png)
i don't really know if this is the right place to write about this, but at least I did

**Comment by lazou** [comment]
Hi @TheKoTech,

in the [releases section](https://github.com/Wufflez/Loki/releases) you can find the precompiled binaries.

**Comment by TheKoTech** [comment]
Sorry, I'm new to github >_<
