### ISSUE TITLE
Loki no longer works on the H&H update

### ISSUE THREAD

**Issue by bjorno43** [Wufflez/Loki#7]
Not sure if you're still keeping up with the game / updates, but I thought I'd give a headsup that it no longer works. From what I've been told, certain data is being compressed now (like map data). Which is probably the biggest reason for it to break. Would be great if you can update it :)

**Comment by xeekworx** [comment]
When I stepped through the code this morning with the debugger, the only section that seemed to fail was skill loading. After commenting that out and the read size sanity checks it seems to work as far as I can tell. I'm not sure if Wufflez is actively developing this anymore since they haven't merged my branch for item searching.

**Comment by xeekworx** [comment]
I looked into it further, actually, it's the food section that's changed in a very minor way. I'll update it in my repo and submit a PR, but you may have to use my repo if Wufflez isn't active.

**Comment by xeekworx** [comment]
Having some problems loading it into Valheim, may take a bit to figure that out, could be simple.

**Comment by xeekworx** [comment]
@bjorno43 if you want to try my release you can here:
https://github.com/xeek-pro/Loki/releases/tag/v0.7.1-xeekworx

**Comment by Sanduhr32** [comment]
@xeekworx hey ugh would you mind keeping the style Wufflez started for versions in Version.cs the variable `ProfileVersion` seems to be the current supported version, while the array of other versions supports older "legacy" versions.

Can't open an issue on your repo, but i think added items beyond a version x should be compatibility matched with the character save file. I don't know how Valheim would behave in such case with newer items in an older version.

**Comment by xeekworx** [comment]
> @xeekworx hey ugh would you mind keeping the style Wufflez started for versions in Version.cs the variable `ProfileVersion` seems to be the current supported version, while the array of other versions supports older "legacy" versions.
> 
> Can't open an issue on your repo, but i think added items beyond a version x should be compatibility matched with the character save file. I don't know how Valheim would behave in such case with newer items in an older version.

It works pretty much as Valheim itself works. The profile is opened as its original version, hence all the version checking for different fields; however it's saved as the new version. If those versions weren't set right, Valheim wouldn't load the profile for H&H. If there is a desire to maintain backwards compatibility from load to save, then the way profiles are saved needs to be refactored.

With respect to the current H&H version, the ProfileVersion is what's saved to the file, not really what's loaded. With the change to how food is loaded and saved, it's not really backwards compatibility.

**Comment by bjorno43** [comment]
@xeekworx Thanks for all your hard work. I'll have a look at it in a few hours as I'm not in the position to test right now. But I'll definitely get back to you about it :)

**Comment by Wufflez** [comment]
Sorry I've been away - I will play some Valheim later tonight and test. I have a feeling that I've missed a major update to the game from these comments :D

**Comment by xeekworx** [comment]
> @xeekworx Thanks for all your hard work. I'll have a look at it in a few hours as I'm not in the position to test right now. But I'll definitely get back to you about it :)

I tested it on a local map, then logged onto my server, and it's working.

> Sorry I've been away - I will play some Valheim later tonight and test. I have a feeling that I've missed a major update to the game from these comments :D
@Wufflez yeah, Hearth & Home came out last week, the main change is the way food works, which also affected the data for it they save to the file.

**Comment by trevorbryant** [comment]
Jumping in to share that @xeekworx's forked fixed does work. It doesn't correct any corrupted character files, but the issues I was having with non-corrupted character files are resolved so far.

**Comment by xeekworx** [comment]
> Jumping in to share that @xeekworx's forked fixed does work. It doesn't correct any corrupted character files, but the issues I was having with non-corrupted character files are resolved so far.

Would you be willing to share one? Maybe I can try and see what’s wrong in it.

**Comment by trevorbryant** [comment]
Sure. Here is the corrupted character file. Note the issue with the skills as I mucked around with the character editor.
[valheim_char_corrupt.tar.gz](https://github.com/Wufflez/Loki/files/7190543/valheim_char_corrupt.tar.gz)
.

**Comment by xeekworx** [comment]
> Sure. Here is the corrupted character file. Note the issue with the skills as I mucked around with the character editor.
> [valheim_char_corrupt.tar.gz](https://github.com/Wufflez/Loki/files/7190543/valheim_char_corrupt.tar.gz)
> .

Looks like it can't find Puke Berries, we may need to add some more for H&H

**Comment by xeekworx** [comment]
@trevorbryant I fixed the save file, and I'll push a change to add puke berries.

**Comment by xeekworx** [comment]
@trevorbryant https://github.com/xeek-pro/Loki/releases/tag/v0.7.2-xeekworx
When you open your corrupted profile, it'll warn you there's a problem, just click Yes to that (multiple times) then save your profile again.

**Comment by xeekworx** [comment]
> @xeekworx hey ugh would you mind keeping the style Wufflez started for versions in Version.cs the variable `ProfileVersion` seems to be the current supported version, while the array of other versions supports older "legacy" versions.

Forgot to point out that that was actually code "very similar" to what's in Valheim ;-)

**Comment by bjorno43** [comment]
@xeekworx Well I've tested your version briefly as promised, and it does seem to work fine with the new characters. But there's no backward compatibility. Character files that haven't been played with after the update are suddenly considered corrupted.

**Comment by xeekworx** [comment]
> u

Are you using Loki on an old save to play an older version of Valheim?

**Comment by bjorno43** [comment]
> 
> 
> > @xeekworx Well I've tested your version briefly as promised, and it does seem to work fine with the new characters. But there's no backward compatibility. Character files that haven't been played with after the update are suddenly considered corrupted.
> 
> Are you using Loki on an old save to play an older version of Valheim?

Of course not. But character files don't get updated until they've been used at least once in game. The game doesn't overwrite them with the H&H update before that. Your version of Loki does load every character I've played with the H&H update, but gives a red "Unknown" for every character I haven't used yet.

**Comment by xeekworx** [comment]
> > > @xeekworx Well I've tested your version briefly as promised, and it does seem to work fine with the new characters. But there's no backward compatibility. Character files that haven't been played with after the update are suddenly considered corrupted.
> > 
> > 
> > Are you using Loki on an old save to play an older version of Valheim?
> 
> Of course not. But character files don't get updated until they've been used at least once in game. The game doesn't overwrite them with the H&H update before that. Your version of Loki does load every character I've played with the H&H update, but gives a red "Unknown" for every character I haven't used yet.

If you're willing to send me one of those characters I can see what's wrong.
The latest version I linked to 0.7.2-xeekworx earlier has a feature where it'll ask you to continue to load the file, as it may just be missing some things that might not hurt it if saved after.

**Comment by bjorno43** [comment]
@xeekworx Ye I can add one of the bugged out ones here
[ripperdoc.zip](https://github.com/Wufflez/Loki/files/7190760/ripperdoc.zip)
.

**Comment by xeekworx** [comment]
> @xeekworx Ye I can add one of the bugged out ones here
> [ripperdoc.zip](https://github.com/Wufflez/Loki/files/7190760/ripperdoc.zip)
> .

I get it now! I may have to make the change tomorrow unless someone else jumps in since I’m out of pocket this evening.

**Comment by bjorno43** [comment]
> 
> 
> > @xeekworx Ye I can add one of the bugged out ones here
> > [ripperdoc.zip](https://github.com/Wufflez/Loki/files/7190760/ripperdoc.zip)
> > .
> 
> I understand you now. I may have to make the change tomorrow unless someone else jumps in since I’m out of pocket this evening.

Sure, take your time m8. I don't actually need that to work, it's just something I noticed so you know where you can improve. That's all. Thanks for all your hard work m8, I really appreciate it! Good night!

**Comment by trevorbryant** [comment]
> @trevorbryant https://github.com/xeek-pro/Loki/releases/tag/v0.7.2-xeekworx
> When you open your corrupted profile, it'll warn you there's a problem, just click Yes to that (multiple times) then save your profile again.

Sorry -- been away. I didn't get the same result you did with your latest build. If you have a recommended offline comms, we can dig deeper here. Let me know.

**Comment by xeekworx** [comment]
> > @trevorbryant https://github.com/xeek-pro/Loki/releases/tag/v0.7.2-xeekworx
> > When you open your corrupted profile, it'll warn you there's a problem, just click Yes to that (multiple times) then save your profile again.
> 
> Sorry -- been away. I didn't get the same result you did with your latest build. If you have a recommended offline comms, we can go back and forth and dig deeper there. Let me know.

I'm on Discord as Xeek#7777

**Comment by xeekworx** [comment]
> > > @xeekworx Ye I can add one of the bugged out ones here
> > > [ripperdoc.zip](https://github.com/Wufflez/Loki/files/7190760/ripperdoc.zip)
> > > .
> > 
> > 
> > I understand you now. I may have to make the change tomorrow unless someone else jumps in since I’m out of pocket this evening.
> 
> Sure, take your time m8. I don't actually need that to work, it's just something I noticed so you know where you can improve. That's all. Thanks for all your hard work m8, I really appreciate it! Good night!

https://github.com/xeek-pro/Loki/releases/tag/v0.7.3-xeekworx
I've separated the compatible load version vs the saved version, so it should load profile versions 33+ like the previous loki release. I've committed this to the H&H #7 PR too. If you want to give it a try, I have my own custom release here:
https://github.com/xeek-pro/Loki/releases/tag/v0.7.3-xeekworx

**Comment by Selectionns** [comment]
Hey thanks, your custom release worked for my old character file whereas latest release here didn't, @xeekworx. Appreciate it amigo.

**Comment by Wufflez** [comment]
I've just released a [new version v0.8](https://github.com/Wufflez/Loki/releases/tag/v0.8-beta) that adds complete support for all of the new Home & Hearth items etc. 

Closing this issue as everything should work with the latest version of the game now.

Please create a new Issue if you spot anything specific that still doesn't work.
